/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppFooter {
    }
    interface AppHeader {
        "inline": boolean;
    }
    interface AppRoot {
    }
    interface DemoFrame {
        "component": string;
        "demo": string;
    }
    interface PageDocs {
        "params": {
    [param: string]: string;
  };
    }
    interface PageHome {
    }
    interface PageNotfound {
    }
    interface SeoTags {
        "description": string;
        "image": string;
        "pageTitle": string;
    }
}
declare global {
    interface HTMLAppFooterElement extends Components.AppFooter, HTMLStencilElement {
    }
    var HTMLAppFooterElement: {
        prototype: HTMLAppFooterElement;
        new (): HTMLAppFooterElement;
    };
    interface HTMLAppHeaderElement extends Components.AppHeader, HTMLStencilElement {
    }
    var HTMLAppHeaderElement: {
        prototype: HTMLAppHeaderElement;
        new (): HTMLAppHeaderElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLDemoFrameElement extends Components.DemoFrame, HTMLStencilElement {
    }
    var HTMLDemoFrameElement: {
        prototype: HTMLDemoFrameElement;
        new (): HTMLDemoFrameElement;
    };
    interface HTMLPageDocsElement extends Components.PageDocs, HTMLStencilElement {
    }
    var HTMLPageDocsElement: {
        prototype: HTMLPageDocsElement;
        new (): HTMLPageDocsElement;
    };
    interface HTMLPageHomeElement extends Components.PageHome, HTMLStencilElement {
    }
    var HTMLPageHomeElement: {
        prototype: HTMLPageHomeElement;
        new (): HTMLPageHomeElement;
    };
    interface HTMLPageNotfoundElement extends Components.PageNotfound, HTMLStencilElement {
    }
    var HTMLPageNotfoundElement: {
        prototype: HTMLPageNotfoundElement;
        new (): HTMLPageNotfoundElement;
    };
    interface HTMLSeoTagsElement extends Components.SeoTags, HTMLStencilElement {
    }
    var HTMLSeoTagsElement: {
        prototype: HTMLSeoTagsElement;
        new (): HTMLSeoTagsElement;
    };
    interface HTMLElementTagNameMap {
        "app-footer": HTMLAppFooterElement;
        "app-header": HTMLAppHeaderElement;
        "app-root": HTMLAppRootElement;
        "demo-frame": HTMLDemoFrameElement;
        "page-docs": HTMLPageDocsElement;
        "page-home": HTMLPageHomeElement;
        "page-notfound": HTMLPageNotfoundElement;
        "seo-tags": HTMLSeoTagsElement;
    }
}
declare namespace LocalJSX {
    interface AppFooter {
    }
    interface AppHeader {
        "inline"?: boolean;
    }
    interface AppRoot {
    }
    interface DemoFrame {
        "component"?: string;
        "demo"?: string;
    }
    interface PageDocs {
        "params"?: {
    [param: string]: string;
  };
    }
    interface PageHome {
    }
    interface PageNotfound {
    }
    interface SeoTags {
        "description"?: string;
        "image"?: string;
        "pageTitle"?: string;
    }
    interface IntrinsicElements {
        "app-footer": AppFooter;
        "app-header": AppHeader;
        "app-root": AppRoot;
        "demo-frame": DemoFrame;
        "page-docs": PageDocs;
        "page-home": PageHome;
        "page-notfound": PageNotfound;
        "seo-tags": SeoTags;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-footer": LocalJSX.AppFooter & JSXBase.HTMLAttributes<HTMLAppFooterElement>;
            "app-header": LocalJSX.AppHeader & JSXBase.HTMLAttributes<HTMLAppHeaderElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "demo-frame": LocalJSX.DemoFrame & JSXBase.HTMLAttributes<HTMLDemoFrameElement>;
            "page-docs": LocalJSX.PageDocs & JSXBase.HTMLAttributes<HTMLPageDocsElement>;
            "page-home": LocalJSX.PageHome & JSXBase.HTMLAttributes<HTMLPageHomeElement>;
            "page-notfound": LocalJSX.PageNotfound & JSXBase.HTMLAttributes<HTMLPageNotfoundElement>;
            "seo-tags": LocalJSX.SeoTags & JSXBase.HTMLAttributes<HTMLSeoTagsElement>;
        }
    }
}
