/* eslint-disable */
/* tslint:disable */
/* auto-generated react proxies */
import { createReactComponent } from './react-component-lib';

import type { JSX } from '@go-ui/core/dist/components';

import { defineCustomElement as defineGoAccordion } from '@go-ui/core/dist/components/go-accordion.js';
import { defineCustomElement as defineGoAccordionItem } from '@go-ui/core/dist/components/go-accordion-item.js';
import { defineCustomElement as defineGoBadge } from '@go-ui/core/dist/components/go-badge.js';
import { defineCustomElement as defineGoBanner } from '@go-ui/core/dist/components/go-banner.js';
import { defineCustomElement as defineGoBlockquote } from '@go-ui/core/dist/components/go-blockquote.js';
import { defineCustomElement as defineGoBreadcrumb } from '@go-ui/core/dist/components/go-breadcrumb.js';
import { defineCustomElement as defineGoButton } from '@go-ui/core/dist/components/go-button.js';
import { defineCustomElement as defineGoButtonGroup } from '@go-ui/core/dist/components/go-button-group.js';
import { defineCustomElement as defineGoCard } from '@go-ui/core/dist/components/go-card.js';
import { defineCustomElement as defineGoCardRow } from '@go-ui/core/dist/components/go-card-row.js';
import { defineCustomElement as defineGoCheckbox } from '@go-ui/core/dist/components/go-checkbox.js';
import { defineCustomElement as defineGoChip } from '@go-ui/core/dist/components/go-chip.js';
import { defineCustomElement as defineGoContent } from '@go-ui/core/dist/components/go-content.js';
import { defineCustomElement as defineGoContentLayout } from '@go-ui/core/dist/components/go-content-layout.js';
import { defineCustomElement as defineGoDialog } from '@go-ui/core/dist/components/go-dialog.js';
import { defineCustomElement as defineGoDropdown } from '@go-ui/core/dist/components/go-dropdown.js';
import { defineCustomElement as defineGoDropdownItem } from '@go-ui/core/dist/components/go-dropdown-item.js';
import { defineCustomElement as defineGoDropdownMenu } from '@go-ui/core/dist/components/go-dropdown-menu.js';
import { defineCustomElement as defineGoDropdownSeparator } from '@go-ui/core/dist/components/go-dropdown-separator.js';
import { defineCustomElement as defineGoField } from '@go-ui/core/dist/components/go-field.js';
import { defineCustomElement as defineGoFieldset } from '@go-ui/core/dist/components/go-fieldset.js';
import { defineCustomElement as defineGoFooter } from '@go-ui/core/dist/components/go-footer.js';
import { defineCustomElement as defineGoGovAuLogo } from '@go-ui/core/dist/components/go-gov-au-logo.js';
import { defineCustomElement as defineGoHeaderBar } from '@go-ui/core/dist/components/go-header-bar.js';
import { defineCustomElement as defineGoHero } from '@go-ui/core/dist/components/go-hero.js';
import { defineCustomElement as defineGoIcon } from '@go-ui/core/dist/components/go-icon.js';
import { defineCustomElement as defineGoInput } from '@go-ui/core/dist/components/go-input.js';
import { defineCustomElement as defineGoLink } from '@go-ui/core/dist/components/go-link.js';
import { defineCustomElement as defineGoMainNav } from '@go-ui/core/dist/components/go-main-nav.js';
import { defineCustomElement as defineGoMd } from '@go-ui/core/dist/components/go-md.js';
import { defineCustomElement as defineGoNavDrawer } from '@go-ui/core/dist/components/go-nav-drawer.js';
import { defineCustomElement as defineGoNavLink } from '@go-ui/core/dist/components/go-nav-link.js';
import { defineCustomElement as defineGoNavList } from '@go-ui/core/dist/components/go-nav-list.js';
import { defineCustomElement as defineGoOverlay } from '@go-ui/core/dist/components/go-overlay.js';
import { defineCustomElement as defineGoProgress } from '@go-ui/core/dist/components/go-progress.js';
import { defineCustomElement as defineGoRadio } from '@go-ui/core/dist/components/go-radio.js';
import { defineCustomElement as defineGoSearchBar } from '@go-ui/core/dist/components/go-search-bar.js';
import { defineCustomElement as defineGoSelect } from '@go-ui/core/dist/components/go-select.js';
import { defineCustomElement as defineGoSkipLink } from '@go-ui/core/dist/components/go-skip-link.js';
import { defineCustomElement as defineGoSpinner } from '@go-ui/core/dist/components/go-spinner.js';
import { defineCustomElement as defineGoSwitch } from '@go-ui/core/dist/components/go-switch.js';
import { defineCustomElement as defineGoTab } from '@go-ui/core/dist/components/go-tab.js';
import { defineCustomElement as defineGoTableWrapper } from '@go-ui/core/dist/components/go-table-wrapper.js';
import { defineCustomElement as defineGoTabs } from '@go-ui/core/dist/components/go-tabs.js';
import { defineCustomElement as defineGoToTop } from '@go-ui/core/dist/components/go-to-top.js';
import { defineCustomElement as defineGoToc } from '@go-ui/core/dist/components/go-toc.js';
import { defineCustomElement as defineGoTooltip } from '@go-ui/core/dist/components/go-tooltip.js';

export const GoAccordion = /*@__PURE__*/createReactComponent<JSX.GoAccordion, HTMLGoAccordionElement>('go-accordion', undefined, undefined, defineGoAccordion);
export const GoAccordionItem = /*@__PURE__*/createReactComponent<JSX.GoAccordionItem, HTMLGoAccordionItemElement>('go-accordion-item', undefined, undefined, defineGoAccordionItem);
export const GoBadge = /*@__PURE__*/createReactComponent<JSX.GoBadge, HTMLGoBadgeElement>('go-badge', undefined, undefined, defineGoBadge);
export const GoBanner = /*@__PURE__*/createReactComponent<JSX.GoBanner, HTMLGoBannerElement>('go-banner', undefined, undefined, defineGoBanner);
export const GoBlockquote = /*@__PURE__*/createReactComponent<JSX.GoBlockquote, HTMLGoBlockquoteElement>('go-blockquote', undefined, undefined, defineGoBlockquote);
export const GoBreadcrumb = /*@__PURE__*/createReactComponent<JSX.GoBreadcrumb, HTMLGoBreadcrumbElement>('go-breadcrumb', undefined, undefined, defineGoBreadcrumb);
export const GoButton = /*@__PURE__*/createReactComponent<JSX.GoButton, HTMLGoButtonElement>('go-button', undefined, undefined, defineGoButton);
export const GoButtonGroup = /*@__PURE__*/createReactComponent<JSX.GoButtonGroup, HTMLGoButtonGroupElement>('go-button-group', undefined, undefined, defineGoButtonGroup);
export const GoCard = /*@__PURE__*/createReactComponent<JSX.GoCard, HTMLGoCardElement>('go-card', undefined, undefined, defineGoCard);
export const GoCardRow = /*@__PURE__*/createReactComponent<JSX.GoCardRow, HTMLGoCardRowElement>('go-card-row', undefined, undefined, defineGoCardRow);
export const GoCheckbox = /*@__PURE__*/createReactComponent<JSX.GoCheckbox, HTMLGoCheckboxElement>('go-checkbox', undefined, undefined, defineGoCheckbox);
export const GoChip = /*@__PURE__*/createReactComponent<JSX.GoChip, HTMLGoChipElement>('go-chip', undefined, undefined, defineGoChip);
export const GoContent = /*@__PURE__*/createReactComponent<JSX.GoContent, HTMLGoContentElement>('go-content', undefined, undefined, defineGoContent);
export const GoContentLayout = /*@__PURE__*/createReactComponent<JSX.GoContentLayout, HTMLGoContentLayoutElement>('go-content-layout', undefined, undefined, defineGoContentLayout);
export const GoDialog = /*@__PURE__*/createReactComponent<JSX.GoDialog, HTMLGoDialogElement>('go-dialog', undefined, undefined, defineGoDialog);
export const GoDropdown = /*@__PURE__*/createReactComponent<JSX.GoDropdown, HTMLGoDropdownElement>('go-dropdown', undefined, undefined, defineGoDropdown);
export const GoDropdownItem = /*@__PURE__*/createReactComponent<JSX.GoDropdownItem, HTMLGoDropdownItemElement>('go-dropdown-item', undefined, undefined, defineGoDropdownItem);
export const GoDropdownMenu = /*@__PURE__*/createReactComponent<JSX.GoDropdownMenu, HTMLGoDropdownMenuElement>('go-dropdown-menu', undefined, undefined, defineGoDropdownMenu);
export const GoDropdownSeparator = /*@__PURE__*/createReactComponent<JSX.GoDropdownSeparator, HTMLGoDropdownSeparatorElement>('go-dropdown-separator', undefined, undefined, defineGoDropdownSeparator);
export const GoField = /*@__PURE__*/createReactComponent<JSX.GoField, HTMLGoFieldElement>('go-field', undefined, undefined, defineGoField);
export const GoFieldset = /*@__PURE__*/createReactComponent<JSX.GoFieldset, HTMLGoFieldsetElement>('go-fieldset', undefined, undefined, defineGoFieldset);
export const GoFooter = /*@__PURE__*/createReactComponent<JSX.GoFooter, HTMLGoFooterElement>('go-footer', undefined, undefined, defineGoFooter);
export const GoGovAuLogo = /*@__PURE__*/createReactComponent<JSX.GoGovAuLogo, HTMLGoGovAuLogoElement>('go-gov-au-logo', undefined, undefined, defineGoGovAuLogo);
export const GoHeaderBar = /*@__PURE__*/createReactComponent<JSX.GoHeaderBar, HTMLGoHeaderBarElement>('go-header-bar', undefined, undefined, defineGoHeaderBar);
export const GoHero = /*@__PURE__*/createReactComponent<JSX.GoHero, HTMLGoHeroElement>('go-hero', undefined, undefined, defineGoHero);
export const GoIcon = /*@__PURE__*/createReactComponent<JSX.GoIcon, HTMLGoIconElement>('go-icon', undefined, undefined, defineGoIcon);
export const GoInput = /*@__PURE__*/createReactComponent<JSX.GoInput, HTMLGoInputElement>('go-input', undefined, undefined, defineGoInput);
export const GoLink = /*@__PURE__*/createReactComponent<JSX.GoLink, HTMLGoLinkElement>('go-link', undefined, undefined, defineGoLink);
export const GoMainNav = /*@__PURE__*/createReactComponent<JSX.GoMainNav, HTMLGoMainNavElement>('go-main-nav', undefined, undefined, defineGoMainNav);
export const GoMd = /*@__PURE__*/createReactComponent<JSX.GoMd, HTMLGoMdElement>('go-md', undefined, undefined, defineGoMd);
export const GoNavDrawer = /*@__PURE__*/createReactComponent<JSX.GoNavDrawer, HTMLGoNavDrawerElement>('go-nav-drawer', undefined, undefined, defineGoNavDrawer);
export const GoNavLink = /*@__PURE__*/createReactComponent<JSX.GoNavLink, HTMLGoNavLinkElement>('go-nav-link', undefined, undefined, defineGoNavLink);
export const GoNavList = /*@__PURE__*/createReactComponent<JSX.GoNavList, HTMLGoNavListElement>('go-nav-list', undefined, undefined, defineGoNavList);
export const GoOverlay = /*@__PURE__*/createReactComponent<JSX.GoOverlay, HTMLGoOverlayElement>('go-overlay', undefined, undefined, defineGoOverlay);
export const GoProgress = /*@__PURE__*/createReactComponent<JSX.GoProgress, HTMLGoProgressElement>('go-progress', undefined, undefined, defineGoProgress);
export const GoRadio = /*@__PURE__*/createReactComponent<JSX.GoRadio, HTMLGoRadioElement>('go-radio', undefined, undefined, defineGoRadio);
export const GoSearchBar = /*@__PURE__*/createReactComponent<JSX.GoSearchBar, HTMLGoSearchBarElement>('go-search-bar', undefined, undefined, defineGoSearchBar);
export const GoSelect = /*@__PURE__*/createReactComponent<JSX.GoSelect, HTMLGoSelectElement>('go-select', undefined, undefined, defineGoSelect);
export const GoSkipLink = /*@__PURE__*/createReactComponent<JSX.GoSkipLink, HTMLGoSkipLinkElement>('go-skip-link', undefined, undefined, defineGoSkipLink);
export const GoSpinner = /*@__PURE__*/createReactComponent<JSX.GoSpinner, HTMLGoSpinnerElement>('go-spinner', undefined, undefined, defineGoSpinner);
export const GoSwitch = /*@__PURE__*/createReactComponent<JSX.GoSwitch, HTMLGoSwitchElement>('go-switch', undefined, undefined, defineGoSwitch);
export const GoTab = /*@__PURE__*/createReactComponent<JSX.GoTab, HTMLGoTabElement>('go-tab', undefined, undefined, defineGoTab);
export const GoTableWrapper = /*@__PURE__*/createReactComponent<JSX.GoTableWrapper, HTMLGoTableWrapperElement>('go-table-wrapper', undefined, undefined, defineGoTableWrapper);
export const GoTabs = /*@__PURE__*/createReactComponent<JSX.GoTabs, HTMLGoTabsElement>('go-tabs', undefined, undefined, defineGoTabs);
export const GoToTop = /*@__PURE__*/createReactComponent<JSX.GoToTop, HTMLGoToTopElement>('go-to-top', undefined, undefined, defineGoToTop);
export const GoToc = /*@__PURE__*/createReactComponent<JSX.GoToc, HTMLGoTocElement>('go-toc', undefined, undefined, defineGoToc);
export const GoTooltip = /*@__PURE__*/createReactComponent<JSX.GoTooltip, HTMLGoTooltipElement>('go-tooltip', undefined, undefined, defineGoTooltip);
