/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DarkModeToggle {
        "inline": boolean;
    }
    interface DemoControls {
    }
}
declare global {
    interface HTMLDarkModeToggleElement extends Components.DarkModeToggle, HTMLStencilElement {
    }
    var HTMLDarkModeToggleElement: {
        prototype: HTMLDarkModeToggleElement;
        new (): HTMLDarkModeToggleElement;
    };
    interface HTMLDemoControlsElement extends Components.DemoControls, HTMLStencilElement {
    }
    var HTMLDemoControlsElement: {
        prototype: HTMLDemoControlsElement;
        new (): HTMLDemoControlsElement;
    };
    interface HTMLElementTagNameMap {
        "dark-mode-toggle": HTMLDarkModeToggleElement;
        "demo-controls": HTMLDemoControlsElement;
    }
}
declare namespace LocalJSX {
    interface DarkModeToggle {
        "inline"?: boolean;
    }
    interface DemoControls {
    }
    interface IntrinsicElements {
        "dark-mode-toggle": DarkModeToggle;
        "demo-controls": DemoControls;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "dark-mode-toggle": LocalJSX.DarkModeToggle & JSXBase.HTMLAttributes<HTMLDarkModeToggleElement>;
            "demo-controls": LocalJSX.DemoControls & JSXBase.HTMLAttributes<HTMLDemoControlsElement>;
        }
    }
}
