# This is a basic workflow to help you get started with Actions

name: Update changelog

# Controls when the workflow will run
on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  release:
    name: Update changelog
    
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.0
        with: 
          node-version: 14.x
        
      # Install deps and cache
      - name: Install dependencies
        uses: bahmutov/npm-install@v1.6.0
        
      # Generate changelog
      - name: Generate changelog
        run: npm run release
